import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowRight, Check, CheckCircle2, ChevronRight, CircleAlert, Eraser, FormInput, Lightbulb, ListChecks, MessageSquareText, RefreshCw, RotateCcw, Send, Sparkles, TestTube2, TextCursorInput, Volume2, VolumeX, X } from "lucide-react";
import { PageToc } from "../components/PageToc";
import { choiceExercises, formExercises, sentenceExercises, situationExercises } from "../data/exercises";
import { speakSpanish, stopSpeech } from "../utils/speech";
import { sitePath } from "../utils/sitePath";

const toc=[{id:"practice-start",label:"Режимы практики"},{id:"recognition",label:"Узнавание"},{id:"forms",label:"Формы"},{id:"sentences",label:"Сборка фразы"},{id:"situations",label:"Ситуационный ответ"}];
const normalize=(value)=>value.trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[¿?¡!.,;:]/g,"").replace(/\s+/g," ");
const shuffle=(items)=>{const copy=[...items];for(let i=copy.length-1;i>0;i-=1){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy};
const sample=(items,count)=>shuffle(items).slice(0,Math.min(count,items.length));
const shuffleChoice=(item)=>{const variants=shuffle(item.options.map((option,index)=>({option,index})));return {...item,options:variants.map(({option})=>option),answer:variants.findIndex(({index})=>index===item.answer)}};
const progressOf=(results)=>({correct:Object.values(results).filter(Boolean).length,answered:Object.keys(results).length});
const choiceSpeechText=(item)=>{const answer=item.options[item.answer];if(!/\p{Script=Cyrillic}/u.test(answer))return answer;const quoted=[...item.prompt.matchAll(/«([^»]+)»/g)].map((match)=>match[1]).find((value)=>!/\p{Script=Cyrillic}/u.test(value));if(quoted)return quoted;const example=item.explanation.split(/\s+[—–]\s+/)[0];return /\p{Script=Cyrillic}/u.test(example)?"":example};

function ScoreBox({correct,answered,total,manual=false}){return <div className="practice-score-box"><span>{manual?"Самопроверка":"Результат"}</span><strong>{correct}<i>/</i>{answered}</strong><small>правильно / отвечено · {total} в наборе</small></div>}

function LevelStatus({audioEnabled,onToggle,...score}){return <div className="practice-level-status"><ScoreBox {...score}/><button className={`practice-audio-toggle ${audioEnabled?"enabled":"muted"}`} onClick={onToggle} aria-pressed={audioEnabled} aria-label={audioEnabled?"Выключить озвучку верных ответов":"Включить озвучку верных ответов"}>{audioEnabled?<Volume2 size={17}/>:<VolumeX size={17}/>}<span>{audioEnabled?"Озвучка включена":"Без озвучки"}</span></button></div>}

function ModeSwitch({label,value,onChange,options}){return <div className="practice-mode-switch"><span>{label}</span><div>{options.map((option)=><button key={option.value} onClick={()=>onChange(option.value)} className={value===option.value?"active":""} aria-pressed={value===option.value}>{option.label}</button>)}</div></div>}

function QuestionCountControl({value,onChange}){return <div className="question-count-control"><span>Количество вопросов</span><div><small>10</small><input type="range" min="10" max="100" step="10" value={value} onChange={(event)=>onChange(Number(event.target.value))} aria-label="Количество вопросов первого уровня"/><small>100</small><output>{value}</output></div></div>}

function ChoiceQuiz({items,mode,onProgress,onNewSession,onCorrect}){
  const [index,setIndex]=useState(0);const [selected,setSelected]=useState(null);const [score,setScore]=useState(0);const [answered,setAnswered]=useState(0);const [finished,setFinished]=useState(false);const timer=useRef(null);
  const item=items[index];
  useEffect(()=>{if(mode!=="mistakes"||selected!==item.answer)return undefined;timer.current=window.setTimeout(()=>{if(index===items.length-1){setFinished(true)}else{setIndex(value=>value+1);setSelected(null)}},420);return()=>window.clearTimeout(timer.current)},[mode,selected,index,item.answer,items.length]);
  const next=()=>{window.clearTimeout(timer.current);if(index===items.length-1){setFinished(true)}else{setIndex(value=>value+1);setSelected(null)}};
  const choose=(option)=>{if(selected!==null)return;const correct=option===item.answer;const nextScore=score+(correct?1:0);const nextAnswered=answered+1;setSelected(option);setScore(nextScore);setAnswered(nextAnswered);onProgress({correct:nextScore,answered:nextAnswered});if(correct)onCorrect(choiceSpeechText(item))};
  useEffect(()=>{const selectByKeyboard=(event)=>{if(selected!==null||finished||event.repeat)return;const target=event.target;if(target instanceof HTMLElement&&(target.matches("input, textarea, select")||target.isContentEditable))return;const match=event.code.match(/^(?:Digit|Numpad)([1-4])$/);if(!match)return;const section=document.getElementById("recognition");const rect=section?.getBoundingClientRect();if(!rect||rect.bottom<=0||rect.top>=window.innerHeight)return;event.preventDefault();choose(Number(match[1])-1)};window.addEventListener("keydown",selectByKeyboard);return()=>window.removeEventListener("keydown",selectByKeyboard)},[selected,finished,choose]);
  const ratio=score/items.length;
  if(finished)return <div className="quiz-finish"><span><CheckCircle2/></span><h3>{score} из {items.length}</h3><p>{ratio>=0.8?"Отличное владение базовыми конструкциями.":ratio>=0.6?"Основа уже работает. Разберите объяснения к ошибкам.":"Стоит ещё раз пройти паттерны и грамматическое ядро."}</p><button onClick={onNewSession}><RefreshCw size={16}/> Новый случайный набор</button></div>;
  const waitsForButton=selected!==null&&(mode==="all"||selected!==item.answer);
  return <div className="choice-quiz"><div className="quiz-progress"><span style={{width:`${((index+1)/items.length)*100}%`}}/><small>{index+1} / {items.length}</small></div><h3>{item.prompt}</h3><div className="choice-options">{item.options.map((option,i)=><button key={option} onClick={()=>choose(i)} className={selected===null?"":i===item.answer?"correct":i===selected?"wrong":"muted"}><span>{i+1}</span>{option}{selected!==null&&i===item.answer&&<Check size={16}/>} {selected===i&&i!==item.answer&&<X size={16}/>}</button>)}</div>{waitsForButton&&<div className={`quiz-explanation ${selected===item.answer?"success":"error"}`}><Lightbulb size={16}/><span>{item.explanation}</span><button onClick={next}>{index===items.length-1?"Результат":"Дальше"}<ChevronRight size={15}/></button></div>}{selected===item.answer&&mode==="mistakes"&&<div className="quiz-auto-next"><CheckCircle2 size={15}/> Верно — открываем следующий вопрос</div>}</div>;
}

function FormItem({item,onResult,onCorrect}){const [value,setValue]=useState("");const [state,setState]=useState(null);const completed=useRef(false);const check=()=>{const result=item.answer.map(normalize).includes(normalize(value))?"correct":"wrong";setState(result);onResult(item.id,result==="correct");if(result==="correct"&&!completed.current){completed.current=true;onCorrect(item.displayAnswer||item.answer[0])}};return <div className={`form-exercise ${state||""}`}><div><span>{item.prompt}</span><small>{item.hint}</small></div><div className="form-answer"><input value={value} onChange={(e)=>{setValue(e.target.value);setState(null)}} onKeyDown={(e)=>e.key==="Enter"&&check()} placeholder="Введите форму…"/><button onClick={check}><Send size={15}/></button></div>{state&&<p>{state==="correct"?<><CheckCircle2/> Верно: {item.displayAnswer||item.answer[0]}</>:<><CircleAlert/> Ответ: {item.displayAnswer||item.answer[0]}. {item.explanation}</>}</p>}</div>}

function SentenceItem({item,onResult,onCorrect}){const [available,setAvailable]=useState(item.tokens.map((token,index)=>({token,index})));const [built,setBuilt]=useState([]);const [state,setState]=useState(null);const completed=useRef(false);const add=(piece)=>{setAvailable(available.filter((x)=>x.index!==piece.index));setBuilt([...built,piece]);setState(null)};const remove=(piece)=>{setBuilt(built.filter((x)=>x.index!==piece.index));setAvailable([...available,piece].sort((a,b)=>a.index-b.index));setState(null)};const reset=()=>{setAvailable(item.tokens.map((token,index)=>({token,index})));setBuilt([]);setState(null)};const check=()=>{const result=normalize(built.map(x=>x.token).join(" "))===normalize(item.answer.join(" "))?"correct":"wrong";setState(result);onResult(item.id,result==="correct");if(result==="correct"&&!completed.current){completed.current=true;onCorrect(item.answer.join(" "))}};return <div className={`sentence-builder ${state||""}`}><span className="builder-translation">{item.translation}</span><div className="built-zone">{built.length?built.map((piece)=><button key={piece.index} onClick={()=>remove(piece)}>{piece.token}</button>):<small>Нажимайте слова в нужном порядке</small>}</div><div className="token-bank">{available.map((piece)=><button key={piece.index} onClick={()=>add(piece)}>{piece.token}</button>)}</div><div className="builder-actions"><button onClick={reset}><RotateCcw size={14}/> Сбросить</button><button className="check-button" onClick={check} disabled={!built.length}>Проверить <ArrowRight size={14}/></button></div>{state&&<p>{state==="correct"?<><CheckCircle2/> Отлично.</>:<><CircleAlert/> Правильный порядок: <span lang="es">{item.answer.join(" ")}</span></>}</p>}</div>}

function ManualSentenceItem({item,onResult,onCorrect}){const [value,setValue]=useState("");const [state,setState]=useState(null);const completed=useRef(false);const expected=item.answer.join(" ");const check=()=>{const result=normalize(value)===normalize(expected)?"correct":"wrong";setState(result);onResult(item.id,result==="correct");if(result==="correct"&&!completed.current){completed.current=true;onCorrect(expected)}};return <div className={`sentence-builder manual-sentence ${state||""}`}><span className="builder-translation">{item.translation}</span><textarea value={value} onChange={(event)=>{setValue(event.target.value);setState(null)}} placeholder="Введите перевод по-испански…"/><div className="builder-actions"><button onClick={()=>{setValue("");setState(null)}}><Eraser size={14}/> Очистить</button><button className="check-button" onClick={check} disabled={!value.trim()}>Проверить <ArrowRight size={14}/></button></div>{state&&<p>{state==="correct"?<><CheckCircle2/> Отлично.</>:<><CircleAlert/> Эталонная формулировка: <span lang="es">{expected}</span></>}</p>}</div>}

function SituationItem({item,onResult}){const [answer,setAnswer]=useState("");const [revealed,setRevealed]=useState(false);const [assessment,setAssessment]=useState(null);const clear=()=>{setAnswer("");setRevealed(false);setAssessment(null);onResult(item.id,null)};const assess=(value)=>{setAssessment(value);onResult(item.id,value)};return <article className="situation-card"><span className="situation-label">Ситуация</span><h3>{item.situation}</h3>{item.useful.length>0&&<div className="useful-words">{item.useful.map((hint)=><span key={`${hint.label}-${hint.word}`}><small>{hint.label}</small><b lang="es">{hint.word}</b></span>)}</div>}<textarea value={answer} onChange={(e)=>setAnswer(e.target.value)} placeholder="Напишите свой вариант по-испански…"/><div className="situation-actions"><button onClick={clear}><Eraser size={14}/> Очистить</button><button onClick={()=>setRevealed(!revealed)}><Lightbulb size={14}/> {revealed?"Скрыть пример":"Показать пример"}</button></div>{revealed&&<div className="sample-answer"><p lang="es">{item.sample}</p><span>{item.translation}</span><small>Это пример, а не единственный правильный ответ.</small><div className="self-assessment"><span>Ваш ответ передаёт тот же смысл?</span><div><button className={assessment===true?"active correct":""} onClick={()=>assess(true)}><Check size={13}/> Да</button><button className={assessment===false?"active repeat":""} onClick={()=>assess(false)}><RotateCcw size={13}/> Повторить</button></div></div></div>}</article>}

export function PracticePage(){
  const [session,setSession]=useState(0);const [recognitionMode,setRecognitionMode]=useState("all");const [recognitionCount,setRecognitionCount]=useState(10);const [sentenceMode,setSentenceMode]=useState("builder");const [audioEnabled,setAudioEnabled]=useState(true);const [recognitionProgress,setRecognitionProgress]=useState({correct:0,answered:0});const [formResults,setFormResults]=useState({});const [sentenceResults,setSentenceResults]=useState({});const [situationResults,setSituationResults]=useState({});
  const total=choiceExercises.length+formExercises.length+sentenceExercises.length+situationExercises.length;
  const choices=useMemo(()=>sample(choiceExercises,recognitionCount).map(shuffleChoice),[session,recognitionCount]);
  const forms=useMemo(()=>sample(formExercises,8),[session]);
  const sentences=useMemo(()=>sample(sentenceExercises,8).map(item=>({...item,tokens:shuffle(item.tokens)})),[session]);
  const situations=useMemo(()=>sample(situationExercises,6),[session]);
  const exercises={choices,forms,sentences,situations};
  const formProgress=progressOf(formResults);const sentenceProgress=progressOf(sentenceResults);const situationProgress=progressOf(situationResults);
  const record=(setter)=>(id,value)=>setter((current)=>{if(value===null){const next={...current};delete next[id];return next}return {...current,[id]:value}});
  useEffect(()=>()=>stopSpeech(),[]);
  const pronounceCorrect=(text)=>{if(audioEnabled&&text)speakSpanish(text)};
  const toggleAudio=()=>{setAudioEnabled((value)=>{if(value)stopSpeech();return !value})};
  const newSession=()=>{stopSpeech();setRecognitionProgress({correct:0,answered:0});setFormResults({});setSentenceResults({});setSituationResults({});setSession(value=>value+1)};
  const changeRecognitionCount=(value)=>{stopSpeech();setRecognitionProgress({correct:0,answered:0});setRecognitionCount(value)};
  const changeSentenceMode=(value)=>{setSentenceMode(value);setSentenceResults({})};
  return <div className="reference-page practice-page">
    <section className="page-hero practice-hero compact-hero"><div className="container"><div className="breadcrumbs"><a href={sitePath("/es-419/")}>Главная</a><span>/</span><span>Практика</span></div><div className="reference-hero-grid"><div><div className="eyebrow"><span>Тесты</span> локальная практика</div><h1><span className="practice-blue-title">Проверить себя.</span></h1><p>Четыре независимых режима проверяют не только узнавание слова, но и способность выбрать форму, собрать фразу и ответить в ситуации.</p></div><div className="hero-index-card practice-index-card"><div><TestTube2 size={18}/><span>Случайная сессия</span></div><strong>{total}</strong><p>заданий в банке</p></div></div></div></section>
    <div className="container reference-layout"><article className="reference-content">
      <section id="practice-start" className="grammar-section"><div className="practice-session-head"><div><div className="section-kicker">Четыре уровня извлечения</div><h2>От выбора до своей реплики</h2></div><button className="new-session-button" onClick={newSession}><RefreshCw size={16}/> Новый набор</button></div><div className="practice-mode-grid"><a href="#recognition"><ListChecks/><strong>Узнавание</strong><span>{exercises.choices.length} из {choiceExercises.length}</span></a><a href="#forms"><TextCursorInput/><strong>Формы</strong><span>{exercises.forms.length} из {formExercises.length}</span></a><a href="#sentences"><FormInput/><strong>Сборка фразы</strong><span>{exercises.sentences.length} из {sentenceExercises.length}</span></a><a href="#situations"><MessageSquareText/><strong>Ситуации</strong><span>{exercises.situations.length} из {situationExercises.length}</span></a></div><div className="practice-note"><Sparkles size={16}/><span>При каждом новом наборе задания и варианты перемешиваются. В сборке фразы испанская пунктуация скрыта полностью, а ситуационный ответ оценивается пользователем после сравнения с образцом.</span></div></section>

      <section id="recognition" className="grammar-section"><div className="practice-level-head"><div><div className="section-kicker">01 · Выбор ответа</div><h2>Узнавание и понимание</h2></div><LevelStatus {...recognitionProgress} total={exercises.choices.length} audioEnabled={audioEnabled} onToggle={toggleAudio}/></div><p className="section-intro">Лексика, паттерны и основные грамматические противопоставления.</p><ModeSwitch label="Когда останавливаться" value={recognitionMode} onChange={setRecognitionMode} options={[{value:"all",label:"После каждого ответа"},{value:"mistakes",label:"Только после ошибки"}]}/><QuestionCountControl value={recognitionCount} onChange={changeRecognitionCount}/><ChoiceQuiz key={`choice-${session}-${recognitionCount}`} items={exercises.choices} mode={recognitionMode} onProgress={setRecognitionProgress} onNewSession={newSession} onCorrect={pronounceCorrect}/></section>

      <section id="forms" className="grammar-section"><div className="practice-level-head"><div><div className="section-kicker">02 · Активная форма</div><h2>Образуйте нужную форму</h2></div><LevelStatus {...formProgress} total={exercises.forms.length} audioEnabled={audioEnabled} onToggle={toggleAudio}/></div><p className="section-intro">Регистр и финальная пунктуация не учитываются; для учебного ответа акцент проверяется мягко.</p><div className="form-practice-list">{exercises.forms.map(item=><FormItem item={item} onResult={record(setFormResults)} onCorrect={pronounceCorrect} key={`${session}-${item.id}`}/>)}</div></section>

      <section id="sentences" className="grammar-section"><div className="practice-level-head"><div><div className="section-kicker">03 · Порядок слов</div><h2>Соберите или напишите предложение</h2></div><LevelStatus {...sentenceProgress} total={exercises.sentences.length} audioEnabled={audioEnabled} onToggle={toggleAudio}/></div><p className="section-intro">В обычном режиме выберите элементы; в продвинутом — напишите испанскую фразу самостоятельно. Пунктуация при проверке не учитывается.</p><ModeSwitch label="Способ ответа" value={sentenceMode} onChange={changeSentenceMode} options={[{value:"builder",label:"Обычный · из слов"},{value:"manual",label:"Продвинутый · вручную"}]}/><div className="sentence-list">{exercises.sentences.map(item=>sentenceMode==="builder"?<SentenceItem item={item} onResult={record(setSentenceResults)} onCorrect={pronounceCorrect} key={`${session}-builder-${item.id}`}/>:<ManualSentenceItem item={item} onResult={record(setSentenceResults)} onCorrect={pronounceCorrect} key={`${session}-manual-${item.id}`}/>)}</div></section>

      <section id="situations" className="grammar-section"><div className="practice-level-head"><div><div className="section-kicker">04 · Собственная речь</div><h2>Ответьте в ситуации</h2></div><ScoreBox {...situationProgress} total={exercises.situations.length} manual/></div><p className="section-intro">До двух опорных слов помогают начать. После показа примера отметьте результат самостоятельно: естественных правильных формулировок может быть несколько.</p><div className="situation-grid">{exercises.situations.map(item=><SituationItem item={item} onResult={record(setSituationResults)} key={`${session}-${item.id}`}/>)}</div></section>
    </article><PageToc items={toc}/></div>
  </div>
}
