import { Archive, ArrowDown, BookMarked, CheckCircle2, Database, FileCheck2, GitBranch, Globe2, Layers3, PackageCheck, Scale, SearchCheck, ShieldCheck, Sparkles, Waypoints } from "lucide-react";
import { PageToc } from "../components/PageToc";

const toc=[{id:"purpose",label:"Назначение"},{id:"principles",label:"Принципы отбора"},{id:"standard",label:"Стандарт es-419"},{id:"pipeline",label:"Путь данных"},{id:"registry",label:"Реестр материалов"},{id:"cards",label:"Карточки"},{id:"limits",label:"Границы версии"}];

const principles=[
  [Scale,"Минимальная достаточность","Включается только материал, без которого пользователь регулярно не может выразить базовую мысль."],
  [SearchCheck,"Частотность с редактурой","Корпусная частотность задаёт основу; практическая ценность может изменить порядок, но не скрыто."],
  [Sparkles,"Естественность","Живая фраза важнее механического требования использовать только уже отобранные слова."],
  [Waypoints,"Генеративность","Предпочтение получают элементы, позволяющие создавать много новых высказываний."],
  [Globe2,"Взаимопонятность","Активный стандарт минимизирует локальные регионализмы и остаётся понятным в Латинской Америке."],
  [ShieldCheck,"Проверяемость","Каждая статья имеет устойчивый идентификатор, статус и связи; ошибка данных должна останавливать публикацию."]
];

const documents=[
  {type:"Нормативный документ",title:"Концепция проекта минимально достаточного изучения языка",role:"Определяет цель, педагогические границы и энциклопедический формат системы.",status:"утверждено"},
  {type:"Нормативный документ",title:"Техническая спецификация",role:"Задаёт сущности, маршруты, связи, сборку, доступность и языковые пакеты.",status:"утверждено"},
  {type:"Нормативный документ",title:"Дорожная карта",role:"Фиксирует последовательность: модель → пилот → стабилизация → масштабирование.",status:"утверждено"},
  {type:"Содержательные данные",title:"Лексическое ядро es-419 v0.1",role:"500 единиц с переводом, формами, примером и редакционной меткой.",status:"рабочая версия"},
  {type:"Производные данные",title:"Библиотека паттернов",role:"Коммуникативные функции, шаблоны, допустимые слоты и связанные примеры.",status:"v1.2"},
  {type:"Производные данные",title:"Диалоги и практика",role:"Естественные ситуации и задания на узнавание, форму и собственную реплику.",status:"v1.2"},
  {type:"Производные данные",title:"Карточки Anki, Quizlet и Полиглот",role:"Форматы .apkg, .txt и .xlsx, собранные из общих данных.",status:"v1.2"}
];

export function SourcesPage(){return <div className="reference-page sources-page">
  <section className="page-hero sources-hero compact-hero"><div className="container"><div className="breadcrumbs"><a href="/es-419/">Главная</a><span>/</span><span>Источники и методика</span></div><div className="reference-hero-grid"><div><div className="eyebrow"><span>Открытая методика</span> нормативная основа</div><h1>Почему именно<br/><em>эти слова и правила?</em></h1><p>Методика показывает не только результат, но и логику отбора, редакционные границы и путь одной записи от источника до страницы сайта.</p></div><div className="hero-index-card slate-card"><div><BookMarked size={18}/><span>Статус комплекта</span></div><strong>v1.2</strong><p>связанный языковой пакет с озвучиваемой лексикой, практикой и готовыми карточками</p></div></div></div></section>
  <div className="container reference-layout"><article className="reference-content">
    <section id="purpose" className="grammar-section"><div className="section-kicker">Назначение</div><h2>Сократить путь до первой осмысленной коммуникации</h2><p className="section-intro large">MDSI не обещает свободного владения после пятисот единиц. Она создаёт функциональную основу: пользователь может сообщить информацию о себе, спросить, выразить желание, возможность, необходимость и мнение, а также говорить о настоящем, завершённом прошлом и планах.</p><div className="method-callout"><span><Layers3/></span><div><strong>Связанная энциклопедия, а не обязательный курс</strong><p>Рекомендуемый порядок помогает ориентироваться, но пользователь свободно переходит между лексикой, грамматикой, паттернами, диалогами и практикой.</p></div></div></section>
    <section id="principles" className="grammar-section"><div className="section-kicker">Редакторская рамка</div><h2>Шесть принципов отбора</h2><div className="principle-grid">{principles.map(([Icon,title,text])=><article key={title}><span><Icon/></span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section id="standard" className="grammar-section"><div className="section-kicker">Языковой стандарт</div><h2>Нейтральный латиноамериканский испанский</h2><div className="standard-grid"><div className="standard-do"><h3><CheckCircle2/> Активно используем</h3><ul><li><b>ustedes</b> как основное множественное «вы»;</li><li>общеупотребительную лексику, понятную в большинстве стран;</li><li>простые нейтральные формулировки;</li><li>значимые варианты с явной пометой.</li></ul></div><div className="standard-reference"><h3><Archive/> Оставляем справочно</h3><ul><li><b>vosotros</b> — для понимания европейского варианта;</li><li>локальные регионализмы — только когда они практически важны;</li><li>расширенные времена и subjuntivo — как следующий уровень;</li><li>редкие значения частотных слов.</li></ul></div></div><div className="grammar-note tone-gray"><Globe2 size={16}/><span>«Нейтральный» — редакционный стандарт взаимопонятности, а не отдельный естественный диалект.</span></div></section>
    <section id="pipeline" className="grammar-section"><div className="section-kicker">Архитектура данных</div><h2>От записи до производных материалов</h2><div className="data-pipeline"><div><Database/><strong>Источник</strong><span>XLSX / будущий YAML</span></div><ArrowDown/><div><FileCheck2/><strong>Проверка</strong><span>схема, формы, ссылки</span></div><ArrowDown/><div><GitBranch/><strong>Граф связей</strong><span>слова, правила, паттерны</span></div><ArrowDown/><div><PackageCheck/><strong>Результаты</strong><span>сайт, поиск, тесты, карточки</span></div></div><p className="pipeline-note">Сайт не хранит независимую копию содержания. Обновление исходной записи должно отражаться во всех представлениях после одной сборки.</p></section>
    <section id="registry" className="grammar-section"><div className="section-kicker">Реестр проекта</div><h2>Нормативные и содержательные материалы</h2><div className="document-register">{documents.map((doc,index)=><article key={doc.title}><span className="doc-index">{String(index+1).padStart(2,"0")}</span><div><small>{doc.type}</small><h3>{doc.title}</h3><p>{doc.role}</p></div><span className={`doc-status ${doc.status.includes("утверж")?"approved":"working"}`}>{doc.status}</span></article>)}</div><div className="source-disclaimer"><ShieldCheck/><p><b>Статус частотности v0.1.</b> Порядок ядра является рабочим сочетанием ранее собранных частотных данных и коммуникативной редакции. Он пригоден для разработки и обучения, но не заявляется как математически идеальный универсальный рейтинг.</p></div></section>
    <section id="cards" className="grammar-section"><div className="section-kicker">Производные материалы</div><h2>Три формата являются частью системы</h2><p className="section-intro">Anki, Quizlet и Полиглот создаются из тех же утверждённых статей, фраз и паттернов: 1 544 карточки Anki и по 1 044 уникальные записи в Quizlet и Полиглоте.</p><div className="anki-card-grid"><article><span>01</span><h3>Anki · два направления</h3><div className="anki-mini"><b lang="es">querer</b><i>⇄</i><p>хотеть · формы · пример</p></div></article><article><span>02</span><h3>Quizlet · одна пара</h3><div className="anki-mini"><b lang="es">la casa</b><i>→</i><p>дом</p></div></article><article><span>03</span><h3>Полиглот · строка XLSX</h3><div className="anki-mini"><b lang="es">la casa</b><i>→</i><p>дом · пример · пустой прогресс</p></div></article></div><a className="inline-callout" href="/es-419/anki/"><span><PackageCheck size={19}/><b>Открыть страницу карточек и скачать .apkg, .txt или .xlsx</b></span></a></section>
    <section id="limits" className="grammar-section"><div className="section-kicker">Честные границы</div><h2>Что входит в текущую версию — и что отложено</h2><div className="scope-table"><div className="scope-row head"><span>Уже входит</span><span>Следующее расширение</span></div><div className="scope-row"><span>500 лексических единиц</span><span>ещё 500–1000 единиц</span></div><div className="scope-row"><span>полные таблицы 128 глаголов</span><span>упражнения на расширенные времена и subjuntivo</span></div><div className="scope-row"><span>ir a + infinitivo, условное и повелительное</span><span>связанные сценарии выбора времени</span></div><div className="scope-row"><span>32 паттерна, 8 диалогов, банк из 2 187 заданий</span><span>аудио и произносительные упражнения</span></div><div className="scope-row"><span>карточки Anki, Quizlet и Полиглот из общей базы</span><span>аудио и выборочные изображения в карточках</span></div><div className="scope-row"><span>локальная работа без аккаунта</span><span>синхронизация и серверный прогресс</span></div></div></section>
  </article><PageToc items={toc}/></div>
  </div>}
